# Generated by Django 6.0.2 on 2026-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitemingredientoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredientoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
